### ISSUE TITLE
Missing positional argument

### ISSUE THREAD

**Issue by hibaalqaysi** [ancasag/ensembleObjectDetection#12]
Hi
I am trying to ensemble multiple yolo models (form k-fold trainings), but whenever I run the cod I get the below error. Apparently when trying to create the xml files (step 4) for prediction the model.predict call is missing the config file. Any thoughts how to incorporate it in the code?

![image](https://user-images.githubusercontent.com/61542014/98300960-54ae0180-1fba-11eb-88df-e958d49ea1fd.png)

**Comment by ancasag** [comment]
Hi, The problem is already solved, it should work without problems. If you have any other problem, do not hesitate to write to me. A greeting.

________________________________
De: hibaalqaysi <notifications@github.com>
Enviado: jueves, 5 de noviembre de 2020 23:04
Para: ancasag/ensembleObjectDetection <ensembleObjectDetection@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Asunto: [ancasag/ensembleObjectDetection] Missing positional argument (#12)


Hi
I am trying to ensemble multiple models yolo models (form k-fold trainings), but whenever I run the cod I get the below error. Apparently when trying to create the xml files (step 4) for prediction the model.predict call is missing the config file. Any thoughts how to incorporate it in the code?

[image]<https://user-images.githubusercontent.com/61542014/98300960-54ae0180-1fba-11eb-88df-e958d49ea1fd.png>
