### ISSUE TITLE
Image width and height incorrect in XML output file

### ISSUE THREAD

**Issue by matt-sharp** [ancasag/ensembleObjectDetection#19]
The XML file containing the detection output from my individual models has swapped the position of the width and height.  I've tried to de-bug the code but I can't find where this error exists.

Here's an example of an image:

![100000003](https://user-images.githubusercontent.com/13571774/110825169-ab3e8b80-828b-11eb-8ff8-e90e61fb2033.jpg)

the annotation file (re-formatted to .txt so that it can be uploaded here):
[100000003.txt](https://github.com/ancasag/ensembleObjectDetection/files/6124717/100000003.txt)

the output from an ensemble method:
[100000003.txt](https://github.com/ancasag/ensembleObjectDetection/files/6124724/100000003.txt)

**Comment by ancasag** [comment]
Hi Matthew,

We have updated the code of our repository and the issue should be fixed now.

Let me know if you have any further problem.

Best,
Ángela

________________________________
De: Matthew Sharp ***@***.***>
Enviado: jueves, 11 de marzo de 2021 18:10
Para: ancasag/ensembleObjectDetection ***@***.***>
Cc: Subscribed ***@***.***>
Asunto: [ancasag/ensembleObjectDetection] Image width and height incorrect in XML output file (#19)


The XML file containing the detection output from my individual models has swapped the position of the width and height. I've tried to de-bug the code but I can't find where this error exists.

Here's an example of an image:

[100000003]<https://user-images.githubusercontent.com/13571774/110825169-ab3e8b80-828b-11eb-8ff8-e90e61fb2033.jpg>

the annotation file (re-formatted to .txt so that it can be uploaded here):
100000003.txt<https://github.com/ancasag/ensembleObjectDetection/files/6124717/100000003.txt>

the output from an ensemble method:
100000003.txt<https://github.com/ancasag/ensembleObjectDetection/files/6124724/100000003.txt>

**Comment by matt-sharp** [comment]
Thanks @ancasag that has now fixed the issue.

**Comment by matt-sharp** [comment]
@ancasag I think there is still one error here:

https://github.com/ancasag/ensembleObjectDetection/blob/f92d0ee16e401bad7a7c57ace104287e90152c5a/TestTimeAugmentation/detect.py#L182

This should be:

`hI, wI, d = frame.shape`

**Comment by ancasag** [comment]
Hi Matthew,

We have updated the code of our repository and the issue should be fixed now.

Let me know if you have any further problem.

Best,
Ángela


________________________________
De: Matthew Sharp ***@***.***>
Enviado: martes, 23 de marzo de 2021 19:04
Para: ancasag/ensembleObjectDetection ***@***.***>
Cc: Ángela Casado García ***@***.***>; Mention ***@***.***>
Asunto: Re: [ancasag/ensembleObjectDetection] Image width and height incorrect in XML output file (#19)


@ancasag<https://github.com/ancasag> I think there is still one error here:

https://github.com/ancasag/ensembleObjectDetection/blob/f92d0ee16e401bad7a7c57ace104287e90152c5a/TestTimeAugmentation/detect.py#L182

This should be:

hI, wI, d = frame.shape

**Comment by matt-sharp** [comment]
Thanks @ancasag
